// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module krnl_bp_krnl_bp_Pipeline_VITIS_LOOP_671_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        chunk,
        u_15_address0,
        u_15_ce0,
        u_15_we0,
        u_15_d0,
        u_15_address1,
        u_15_ce1,
        u_15_q1,
        u_14_address0,
        u_14_ce0,
        u_14_we0,
        u_14_d0,
        u_14_address1,
        u_14_ce1,
        u_14_q1,
        u_13_address0,
        u_13_ce0,
        u_13_we0,
        u_13_d0,
        u_13_address1,
        u_13_ce1,
        u_13_q1,
        u_12_address0,
        u_12_ce0,
        u_12_we0,
        u_12_d0,
        u_12_address1,
        u_12_ce1,
        u_12_q1,
        u_11_address0,
        u_11_ce0,
        u_11_we0,
        u_11_d0,
        u_11_address1,
        u_11_ce1,
        u_11_q1,
        u_10_address0,
        u_10_ce0,
        u_10_we0,
        u_10_d0,
        u_10_address1,
        u_10_ce1,
        u_10_q1,
        u_9_address0,
        u_9_ce0,
        u_9_we0,
        u_9_d0,
        u_9_address1,
        u_9_ce1,
        u_9_q1,
        u_8_address0,
        u_8_ce0,
        u_8_we0,
        u_8_d0,
        u_8_address1,
        u_8_ce1,
        u_8_q1,
        u_7_address0,
        u_7_ce0,
        u_7_we0,
        u_7_d0,
        u_7_address1,
        u_7_ce1,
        u_7_q1,
        u_6_address0,
        u_6_ce0,
        u_6_we0,
        u_6_d0,
        u_6_address1,
        u_6_ce1,
        u_6_q1,
        u_5_address0,
        u_5_ce0,
        u_5_we0,
        u_5_d0,
        u_5_address1,
        u_5_ce1,
        u_5_q1,
        u_4_address0,
        u_4_ce0,
        u_4_we0,
        u_4_d0,
        u_4_address1,
        u_4_ce1,
        u_4_q1,
        u_3_address0,
        u_3_ce0,
        u_3_we0,
        u_3_d0,
        u_3_address1,
        u_3_ce1,
        u_3_q1,
        u_2_address0,
        u_2_ce0,
        u_2_we0,
        u_2_d0,
        u_2_address1,
        u_2_ce1,
        u_2_q1,
        u_1_address0,
        u_1_ce0,
        u_1_we0,
        u_1_d0,
        u_1_address1,
        u_1_ce1,
        u_1_q1,
        u_address0,
        u_ce0,
        u_we0,
        u_d0,
        u_address1,
        u_ce1,
        u_q1,
        x_hat_z_address0,
        x_hat_z_ce0,
        x_hat_z_q0,
        x_hat_z_1_address0,
        x_hat_z_1_ce0,
        x_hat_z_1_q0,
        x_hat_z_2_address0,
        x_hat_z_2_ce0,
        x_hat_z_2_q0,
        x_hat_z_3_address0,
        x_hat_z_3_ce0,
        x_hat_z_3_q0,
        x_hat_z_4_address0,
        x_hat_z_4_ce0,
        x_hat_z_4_q0,
        x_hat_z_5_address0,
        x_hat_z_5_ce0,
        x_hat_z_5_q0,
        x_hat_z_6_address0,
        x_hat_z_6_ce0,
        x_hat_z_6_q0,
        x_hat_z_7_address0,
        x_hat_z_7_ce0,
        x_hat_z_7_q0,
        x_hat_z_8_address0,
        x_hat_z_8_ce0,
        x_hat_z_8_q0,
        x_hat_z_9_address0,
        x_hat_z_9_ce0,
        x_hat_z_9_q0,
        x_hat_z_10_address0,
        x_hat_z_10_ce0,
        x_hat_z_10_q0,
        x_hat_z_11_address0,
        x_hat_z_11_ce0,
        x_hat_z_11_q0,
        x_hat_z_12_address0,
        x_hat_z_12_ce0,
        x_hat_z_12_q0,
        x_hat_z_13_address0,
        x_hat_z_13_ce0,
        x_hat_z_13_q0,
        x_hat_z_14_address0,
        x_hat_z_14_ce0,
        x_hat_z_14_q0,
        x_hat_z_15_address0,
        x_hat_z_15_ce0,
        x_hat_z_15_q0,
        grp_fu_1657_p_din0,
        grp_fu_1657_p_din1,
        grp_fu_1657_p_opcode,
        grp_fu_1657_p_dout0,
        grp_fu_1657_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] chunk;
output  [2:0] u_15_address0;
output   u_15_ce0;
output   u_15_we0;
output  [31:0] u_15_d0;
output  [2:0] u_15_address1;
output   u_15_ce1;
input  [31:0] u_15_q1;
output  [2:0] u_14_address0;
output   u_14_ce0;
output   u_14_we0;
output  [31:0] u_14_d0;
output  [2:0] u_14_address1;
output   u_14_ce1;
input  [31:0] u_14_q1;
output  [2:0] u_13_address0;
output   u_13_ce0;
output   u_13_we0;
output  [31:0] u_13_d0;
output  [2:0] u_13_address1;
output   u_13_ce1;
input  [31:0] u_13_q1;
output  [2:0] u_12_address0;
output   u_12_ce0;
output   u_12_we0;
output  [31:0] u_12_d0;
output  [2:0] u_12_address1;
output   u_12_ce1;
input  [31:0] u_12_q1;
output  [2:0] u_11_address0;
output   u_11_ce0;
output   u_11_we0;
output  [31:0] u_11_d0;
output  [2:0] u_11_address1;
output   u_11_ce1;
input  [31:0] u_11_q1;
output  [2:0] u_10_address0;
output   u_10_ce0;
output   u_10_we0;
output  [31:0] u_10_d0;
output  [2:0] u_10_address1;
output   u_10_ce1;
input  [31:0] u_10_q1;
output  [2:0] u_9_address0;
output   u_9_ce0;
output   u_9_we0;
output  [31:0] u_9_d0;
output  [2:0] u_9_address1;
output   u_9_ce1;
input  [31:0] u_9_q1;
output  [2:0] u_8_address0;
output   u_8_ce0;
output   u_8_we0;
output  [31:0] u_8_d0;
output  [2:0] u_8_address1;
output   u_8_ce1;
input  [31:0] u_8_q1;
output  [2:0] u_7_address0;
output   u_7_ce0;
output   u_7_we0;
output  [31:0] u_7_d0;
output  [2:0] u_7_address1;
output   u_7_ce1;
input  [31:0] u_7_q1;
output  [2:0] u_6_address0;
output   u_6_ce0;
output   u_6_we0;
output  [31:0] u_6_d0;
output  [2:0] u_6_address1;
output   u_6_ce1;
input  [31:0] u_6_q1;
output  [2:0] u_5_address0;
output   u_5_ce0;
output   u_5_we0;
output  [31:0] u_5_d0;
output  [2:0] u_5_address1;
output   u_5_ce1;
input  [31:0] u_5_q1;
output  [2:0] u_4_address0;
output   u_4_ce0;
output   u_4_we0;
output  [31:0] u_4_d0;
output  [2:0] u_4_address1;
output   u_4_ce1;
input  [31:0] u_4_q1;
output  [2:0] u_3_address0;
output   u_3_ce0;
output   u_3_we0;
output  [31:0] u_3_d0;
output  [2:0] u_3_address1;
output   u_3_ce1;
input  [31:0] u_3_q1;
output  [2:0] u_2_address0;
output   u_2_ce0;
output   u_2_we0;
output  [31:0] u_2_d0;
output  [2:0] u_2_address1;
output   u_2_ce1;
input  [31:0] u_2_q1;
output  [2:0] u_1_address0;
output   u_1_ce0;
output   u_1_we0;
output  [31:0] u_1_d0;
output  [2:0] u_1_address1;
output   u_1_ce1;
input  [31:0] u_1_q1;
output  [2:0] u_address0;
output   u_ce0;
output   u_we0;
output  [31:0] u_d0;
output  [2:0] u_address1;
output   u_ce1;
input  [31:0] u_q1;
output  [2:0] x_hat_z_address0;
output   x_hat_z_ce0;
input  [31:0] x_hat_z_q0;
output  [2:0] x_hat_z_1_address0;
output   x_hat_z_1_ce0;
input  [31:0] x_hat_z_1_q0;
output  [2:0] x_hat_z_2_address0;
output   x_hat_z_2_ce0;
input  [31:0] x_hat_z_2_q0;
output  [2:0] x_hat_z_3_address0;
output   x_hat_z_3_ce0;
input  [31:0] x_hat_z_3_q0;
output  [2:0] x_hat_z_4_address0;
output   x_hat_z_4_ce0;
input  [31:0] x_hat_z_4_q0;
output  [2:0] x_hat_z_5_address0;
output   x_hat_z_5_ce0;
input  [31:0] x_hat_z_5_q0;
output  [2:0] x_hat_z_6_address0;
output   x_hat_z_6_ce0;
input  [31:0] x_hat_z_6_q0;
output  [2:0] x_hat_z_7_address0;
output   x_hat_z_7_ce0;
input  [31:0] x_hat_z_7_q0;
output  [2:0] x_hat_z_8_address0;
output   x_hat_z_8_ce0;
input  [31:0] x_hat_z_8_q0;
output  [2:0] x_hat_z_9_address0;
output   x_hat_z_9_ce0;
input  [31:0] x_hat_z_9_q0;
output  [2:0] x_hat_z_10_address0;
output   x_hat_z_10_ce0;
input  [31:0] x_hat_z_10_q0;
output  [2:0] x_hat_z_11_address0;
output   x_hat_z_11_ce0;
input  [31:0] x_hat_z_11_q0;
output  [2:0] x_hat_z_12_address0;
output   x_hat_z_12_ce0;
input  [31:0] x_hat_z_12_q0;
output  [2:0] x_hat_z_13_address0;
output   x_hat_z_13_ce0;
input  [31:0] x_hat_z_13_q0;
output  [2:0] x_hat_z_14_address0;
output   x_hat_z_14_ce0;
input  [31:0] x_hat_z_14_q0;
output  [2:0] x_hat_z_15_address0;
output   x_hat_z_15_ce0;
input  [31:0] x_hat_z_15_q0;
output  [31:0] grp_fu_1657_p_din0;
output  [31:0] grp_fu_1657_p_din1;
output  [0:0] grp_fu_1657_p_opcode;
input  [31:0] grp_fu_1657_p_dout0;
output   grp_fu_1657_p_ce;

reg ap_idle;
reg u_15_ce0;
reg u_15_we0;
reg u_15_ce1;
reg u_14_ce0;
reg u_14_we0;
reg u_14_ce1;
reg u_13_ce0;
reg u_13_we0;
reg u_13_ce1;
reg u_12_ce0;
reg u_12_we0;
reg u_12_ce1;
reg u_11_ce0;
reg u_11_we0;
reg u_11_ce1;
reg u_10_ce0;
reg u_10_we0;
reg u_10_ce1;
reg u_9_ce0;
reg u_9_we0;
reg u_9_ce1;
reg u_8_ce0;
reg u_8_we0;
reg u_8_ce1;
reg u_7_ce0;
reg u_7_we0;
reg u_7_ce1;
reg u_6_ce0;
reg u_6_we0;
reg u_6_ce1;
reg u_5_ce0;
reg u_5_we0;
reg u_5_ce1;
reg u_4_ce0;
reg u_4_we0;
reg u_4_ce1;
reg u_3_ce0;
reg u_3_we0;
reg u_3_ce1;
reg u_2_ce0;
reg u_2_we0;
reg u_2_ce1;
reg u_1_ce0;
reg u_1_we0;
reg u_1_ce1;
reg u_ce0;
reg u_we0;
reg u_ce1;
reg x_hat_z_ce0;
reg x_hat_z_1_ce0;
reg x_hat_z_2_ce0;
reg x_hat_z_3_ce0;
reg x_hat_z_4_ce0;
reg x_hat_z_5_ce0;
reg x_hat_z_6_ce0;
reg x_hat_z_7_ce0;
reg x_hat_z_8_ce0;
reg x_hat_z_9_ce0;
reg x_hat_z_10_ce0;
reg x_hat_z_11_ce0;
reg x_hat_z_12_ce0;
reg x_hat_z_13_ce0;
reg x_hat_z_14_ce0;
reg x_hat_z_15_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln671_fu_636_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln671_fu_648_p1;
reg   [3:0] trunc_ln671_reg_856;
reg   [3:0] trunc_ln671_reg_856_pp0_iter1_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter2_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter3_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter4_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter5_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter6_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter7_reg;
reg   [3:0] trunc_ln671_reg_856_pp0_iter8_reg;
reg   [2:0] u_addr_reg_942;
reg   [2:0] u_addr_reg_942_pp0_iter1_reg;
reg   [2:0] u_addr_reg_942_pp0_iter2_reg;
reg   [2:0] u_addr_reg_942_pp0_iter3_reg;
reg   [2:0] u_addr_reg_942_pp0_iter4_reg;
reg   [2:0] u_addr_reg_942_pp0_iter5_reg;
reg   [2:0] u_addr_reg_942_pp0_iter6_reg;
reg   [2:0] u_addr_reg_942_pp0_iter7_reg;
reg   [2:0] u_addr_reg_942_pp0_iter8_reg;
reg   [2:0] u_1_addr_reg_948;
reg   [2:0] u_1_addr_reg_948_pp0_iter1_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter2_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter3_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter4_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter5_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter6_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter7_reg;
reg   [2:0] u_1_addr_reg_948_pp0_iter8_reg;
reg   [2:0] u_2_addr_reg_954;
reg   [2:0] u_2_addr_reg_954_pp0_iter1_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter2_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter3_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter4_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter5_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter6_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter7_reg;
reg   [2:0] u_2_addr_reg_954_pp0_iter8_reg;
reg   [2:0] u_3_addr_reg_960;
reg   [2:0] u_3_addr_reg_960_pp0_iter1_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter2_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter3_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter4_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter5_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter6_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter7_reg;
reg   [2:0] u_3_addr_reg_960_pp0_iter8_reg;
reg   [2:0] u_4_addr_reg_966;
reg   [2:0] u_4_addr_reg_966_pp0_iter1_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter2_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter3_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter4_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter5_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter6_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter7_reg;
reg   [2:0] u_4_addr_reg_966_pp0_iter8_reg;
reg   [2:0] u_5_addr_reg_972;
reg   [2:0] u_5_addr_reg_972_pp0_iter1_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter2_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter3_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter4_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter5_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter6_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter7_reg;
reg   [2:0] u_5_addr_reg_972_pp0_iter8_reg;
reg   [2:0] u_6_addr_reg_978;
reg   [2:0] u_6_addr_reg_978_pp0_iter1_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter2_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter3_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter4_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter5_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter6_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter7_reg;
reg   [2:0] u_6_addr_reg_978_pp0_iter8_reg;
reg   [2:0] u_7_addr_reg_984;
reg   [2:0] u_7_addr_reg_984_pp0_iter1_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter2_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter3_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter4_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter5_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter6_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter7_reg;
reg   [2:0] u_7_addr_reg_984_pp0_iter8_reg;
reg   [2:0] u_8_addr_reg_990;
reg   [2:0] u_8_addr_reg_990_pp0_iter1_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter2_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter3_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter4_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter5_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter6_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter7_reg;
reg   [2:0] u_8_addr_reg_990_pp0_iter8_reg;
reg   [2:0] u_9_addr_reg_996;
reg   [2:0] u_9_addr_reg_996_pp0_iter1_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter2_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter3_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter4_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter5_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter6_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter7_reg;
reg   [2:0] u_9_addr_reg_996_pp0_iter8_reg;
reg   [2:0] u_10_addr_reg_1002;
reg   [2:0] u_10_addr_reg_1002_pp0_iter1_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter2_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter3_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter4_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter5_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter6_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter7_reg;
reg   [2:0] u_10_addr_reg_1002_pp0_iter8_reg;
reg   [2:0] u_11_addr_reg_1008;
reg   [2:0] u_11_addr_reg_1008_pp0_iter1_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter2_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter3_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter4_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter5_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter6_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter7_reg;
reg   [2:0] u_11_addr_reg_1008_pp0_iter8_reg;
reg   [2:0] u_12_addr_reg_1014;
reg   [2:0] u_12_addr_reg_1014_pp0_iter1_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter2_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter3_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter4_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter5_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter6_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter7_reg;
reg   [2:0] u_12_addr_reg_1014_pp0_iter8_reg;
reg   [2:0] u_13_addr_reg_1020;
reg   [2:0] u_13_addr_reg_1020_pp0_iter1_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter2_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter3_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter4_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter5_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter6_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter7_reg;
reg   [2:0] u_13_addr_reg_1020_pp0_iter8_reg;
reg   [2:0] u_14_addr_reg_1026;
reg   [2:0] u_14_addr_reg_1026_pp0_iter1_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter2_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter3_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter4_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter5_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter6_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter7_reg;
reg   [2:0] u_14_addr_reg_1026_pp0_iter8_reg;
reg   [2:0] u_15_addr_reg_1032;
reg   [2:0] u_15_addr_reg_1032_pp0_iter1_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter2_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter3_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter4_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter5_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter6_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter7_reg;
reg   [2:0] u_15_addr_reg_1032_pp0_iter8_reg;
wire   [31:0] tmp_s_fu_703_p35;
reg   [31:0] tmp_s_reg_1038;
wire   [31:0] tmp_4_fu_774_p35;
reg   [31:0] tmp_4_reg_1043;
reg   [31:0] add4_reg_1048;
wire   [63:0] zext_ln671_fu_662_p1;
wire    ap_block_pp0_stage0;
reg   [30:0] i_fu_134;
wire   [30:0] add_ln671_fu_642_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_i_2;
wire   [2:0] lshr_ln_fu_652_p4;
wire   [31:0] tmp_s_fu_703_p33;
wire   [31:0] tmp_4_fu_774_p33;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [3:0] tmp_s_fu_703_p1;
wire   [3:0] tmp_s_fu_703_p3;
wire   [3:0] tmp_s_fu_703_p5;
wire   [3:0] tmp_s_fu_703_p7;
wire   [3:0] tmp_s_fu_703_p9;
wire   [3:0] tmp_s_fu_703_p11;
wire   [3:0] tmp_s_fu_703_p13;
wire   [3:0] tmp_s_fu_703_p15;
wire  signed [3:0] tmp_s_fu_703_p17;
wire  signed [3:0] tmp_s_fu_703_p19;
wire  signed [3:0] tmp_s_fu_703_p21;
wire  signed [3:0] tmp_s_fu_703_p23;
wire  signed [3:0] tmp_s_fu_703_p25;
wire  signed [3:0] tmp_s_fu_703_p27;
wire  signed [3:0] tmp_s_fu_703_p29;
wire  signed [3:0] tmp_s_fu_703_p31;
wire   [3:0] tmp_4_fu_774_p1;
wire   [3:0] tmp_4_fu_774_p3;
wire   [3:0] tmp_4_fu_774_p5;
wire   [3:0] tmp_4_fu_774_p7;
wire   [3:0] tmp_4_fu_774_p9;
wire   [3:0] tmp_4_fu_774_p11;
wire   [3:0] tmp_4_fu_774_p13;
wire   [3:0] tmp_4_fu_774_p15;
wire  signed [3:0] tmp_4_fu_774_p17;
wire  signed [3:0] tmp_4_fu_774_p19;
wire  signed [3:0] tmp_4_fu_774_p21;
wire  signed [3:0] tmp_4_fu_774_p23;
wire  signed [3:0] tmp_4_fu_774_p25;
wire  signed [3:0] tmp_4_fu_774_p27;
wire  signed [3:0] tmp_4_fu_774_p29;
wire  signed [3:0] tmp_4_fu_774_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 i_fu_134 = 31'd0;
#0 ap_done_reg = 1'b0;
end

krnl_bp_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U360(
    .din0(x_hat_z_q0),
    .din1(x_hat_z_1_q0),
    .din2(x_hat_z_2_q0),
    .din3(x_hat_z_3_q0),
    .din4(x_hat_z_4_q0),
    .din5(x_hat_z_5_q0),
    .din6(x_hat_z_6_q0),
    .din7(x_hat_z_7_q0),
    .din8(x_hat_z_8_q0),
    .din9(x_hat_z_9_q0),
    .din10(x_hat_z_10_q0),
    .din11(x_hat_z_11_q0),
    .din12(x_hat_z_12_q0),
    .din13(x_hat_z_13_q0),
    .din14(x_hat_z_14_q0),
    .din15(x_hat_z_15_q0),
    .def(tmp_s_fu_703_p33),
    .sel(trunc_ln671_reg_856),
    .dout(tmp_s_fu_703_p35)
);

krnl_bp_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U361(
    .din0(u_q1),
    .din1(u_1_q1),
    .din2(u_2_q1),
    .din3(u_3_q1),
    .din4(u_4_q1),
    .din5(u_5_q1),
    .din6(u_6_q1),
    .din7(u_7_q1),
    .din8(u_8_q1),
    .din9(u_9_q1),
    .din10(u_10_q1),
    .din11(u_11_q1),
    .din12(u_12_q1),
    .din13(u_13_q1),
    .din14(u_14_q1),
    .din15(u_15_q1),
    .def(tmp_4_fu_774_p33),
    .sel(trunc_ln671_reg_856),
    .dout(tmp_4_fu_774_p35)
);

krnl_bp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln671_fu_636_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_134 <= add_ln671_fu_642_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_134 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add4_reg_1048 <= grp_fu_1657_p_dout0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        trunc_ln671_reg_856_pp0_iter2_reg <= trunc_ln671_reg_856_pp0_iter1_reg;
        trunc_ln671_reg_856_pp0_iter3_reg <= trunc_ln671_reg_856_pp0_iter2_reg;
        trunc_ln671_reg_856_pp0_iter4_reg <= trunc_ln671_reg_856_pp0_iter3_reg;
        trunc_ln671_reg_856_pp0_iter5_reg <= trunc_ln671_reg_856_pp0_iter4_reg;
        trunc_ln671_reg_856_pp0_iter6_reg <= trunc_ln671_reg_856_pp0_iter5_reg;
        trunc_ln671_reg_856_pp0_iter7_reg <= trunc_ln671_reg_856_pp0_iter6_reg;
        trunc_ln671_reg_856_pp0_iter8_reg <= trunc_ln671_reg_856_pp0_iter7_reg;
        u_10_addr_reg_1002_pp0_iter2_reg <= u_10_addr_reg_1002_pp0_iter1_reg;
        u_10_addr_reg_1002_pp0_iter3_reg <= u_10_addr_reg_1002_pp0_iter2_reg;
        u_10_addr_reg_1002_pp0_iter4_reg <= u_10_addr_reg_1002_pp0_iter3_reg;
        u_10_addr_reg_1002_pp0_iter5_reg <= u_10_addr_reg_1002_pp0_iter4_reg;
        u_10_addr_reg_1002_pp0_iter6_reg <= u_10_addr_reg_1002_pp0_iter5_reg;
        u_10_addr_reg_1002_pp0_iter7_reg <= u_10_addr_reg_1002_pp0_iter6_reg;
        u_10_addr_reg_1002_pp0_iter8_reg <= u_10_addr_reg_1002_pp0_iter7_reg;
        u_11_addr_reg_1008_pp0_iter2_reg <= u_11_addr_reg_1008_pp0_iter1_reg;
        u_11_addr_reg_1008_pp0_iter3_reg <= u_11_addr_reg_1008_pp0_iter2_reg;
        u_11_addr_reg_1008_pp0_iter4_reg <= u_11_addr_reg_1008_pp0_iter3_reg;
        u_11_addr_reg_1008_pp0_iter5_reg <= u_11_addr_reg_1008_pp0_iter4_reg;
        u_11_addr_reg_1008_pp0_iter6_reg <= u_11_addr_reg_1008_pp0_iter5_reg;
        u_11_addr_reg_1008_pp0_iter7_reg <= u_11_addr_reg_1008_pp0_iter6_reg;
        u_11_addr_reg_1008_pp0_iter8_reg <= u_11_addr_reg_1008_pp0_iter7_reg;
        u_12_addr_reg_1014_pp0_iter2_reg <= u_12_addr_reg_1014_pp0_iter1_reg;
        u_12_addr_reg_1014_pp0_iter3_reg <= u_12_addr_reg_1014_pp0_iter2_reg;
        u_12_addr_reg_1014_pp0_iter4_reg <= u_12_addr_reg_1014_pp0_iter3_reg;
        u_12_addr_reg_1014_pp0_iter5_reg <= u_12_addr_reg_1014_pp0_iter4_reg;
        u_12_addr_reg_1014_pp0_iter6_reg <= u_12_addr_reg_1014_pp0_iter5_reg;
        u_12_addr_reg_1014_pp0_iter7_reg <= u_12_addr_reg_1014_pp0_iter6_reg;
        u_12_addr_reg_1014_pp0_iter8_reg <= u_12_addr_reg_1014_pp0_iter7_reg;
        u_13_addr_reg_1020_pp0_iter2_reg <= u_13_addr_reg_1020_pp0_iter1_reg;
        u_13_addr_reg_1020_pp0_iter3_reg <= u_13_addr_reg_1020_pp0_iter2_reg;
        u_13_addr_reg_1020_pp0_iter4_reg <= u_13_addr_reg_1020_pp0_iter3_reg;
        u_13_addr_reg_1020_pp0_iter5_reg <= u_13_addr_reg_1020_pp0_iter4_reg;
        u_13_addr_reg_1020_pp0_iter6_reg <= u_13_addr_reg_1020_pp0_iter5_reg;
        u_13_addr_reg_1020_pp0_iter7_reg <= u_13_addr_reg_1020_pp0_iter6_reg;
        u_13_addr_reg_1020_pp0_iter8_reg <= u_13_addr_reg_1020_pp0_iter7_reg;
        u_14_addr_reg_1026_pp0_iter2_reg <= u_14_addr_reg_1026_pp0_iter1_reg;
        u_14_addr_reg_1026_pp0_iter3_reg <= u_14_addr_reg_1026_pp0_iter2_reg;
        u_14_addr_reg_1026_pp0_iter4_reg <= u_14_addr_reg_1026_pp0_iter3_reg;
        u_14_addr_reg_1026_pp0_iter5_reg <= u_14_addr_reg_1026_pp0_iter4_reg;
        u_14_addr_reg_1026_pp0_iter6_reg <= u_14_addr_reg_1026_pp0_iter5_reg;
        u_14_addr_reg_1026_pp0_iter7_reg <= u_14_addr_reg_1026_pp0_iter6_reg;
        u_14_addr_reg_1026_pp0_iter8_reg <= u_14_addr_reg_1026_pp0_iter7_reg;
        u_15_addr_reg_1032_pp0_iter2_reg <= u_15_addr_reg_1032_pp0_iter1_reg;
        u_15_addr_reg_1032_pp0_iter3_reg <= u_15_addr_reg_1032_pp0_iter2_reg;
        u_15_addr_reg_1032_pp0_iter4_reg <= u_15_addr_reg_1032_pp0_iter3_reg;
        u_15_addr_reg_1032_pp0_iter5_reg <= u_15_addr_reg_1032_pp0_iter4_reg;
        u_15_addr_reg_1032_pp0_iter6_reg <= u_15_addr_reg_1032_pp0_iter5_reg;
        u_15_addr_reg_1032_pp0_iter7_reg <= u_15_addr_reg_1032_pp0_iter6_reg;
        u_15_addr_reg_1032_pp0_iter8_reg <= u_15_addr_reg_1032_pp0_iter7_reg;
        u_1_addr_reg_948_pp0_iter2_reg <= u_1_addr_reg_948_pp0_iter1_reg;
        u_1_addr_reg_948_pp0_iter3_reg <= u_1_addr_reg_948_pp0_iter2_reg;
        u_1_addr_reg_948_pp0_iter4_reg <= u_1_addr_reg_948_pp0_iter3_reg;
        u_1_addr_reg_948_pp0_iter5_reg <= u_1_addr_reg_948_pp0_iter4_reg;
        u_1_addr_reg_948_pp0_iter6_reg <= u_1_addr_reg_948_pp0_iter5_reg;
        u_1_addr_reg_948_pp0_iter7_reg <= u_1_addr_reg_948_pp0_iter6_reg;
        u_1_addr_reg_948_pp0_iter8_reg <= u_1_addr_reg_948_pp0_iter7_reg;
        u_2_addr_reg_954_pp0_iter2_reg <= u_2_addr_reg_954_pp0_iter1_reg;
        u_2_addr_reg_954_pp0_iter3_reg <= u_2_addr_reg_954_pp0_iter2_reg;
        u_2_addr_reg_954_pp0_iter4_reg <= u_2_addr_reg_954_pp0_iter3_reg;
        u_2_addr_reg_954_pp0_iter5_reg <= u_2_addr_reg_954_pp0_iter4_reg;
        u_2_addr_reg_954_pp0_iter6_reg <= u_2_addr_reg_954_pp0_iter5_reg;
        u_2_addr_reg_954_pp0_iter7_reg <= u_2_addr_reg_954_pp0_iter6_reg;
        u_2_addr_reg_954_pp0_iter8_reg <= u_2_addr_reg_954_pp0_iter7_reg;
        u_3_addr_reg_960_pp0_iter2_reg <= u_3_addr_reg_960_pp0_iter1_reg;
        u_3_addr_reg_960_pp0_iter3_reg <= u_3_addr_reg_960_pp0_iter2_reg;
        u_3_addr_reg_960_pp0_iter4_reg <= u_3_addr_reg_960_pp0_iter3_reg;
        u_3_addr_reg_960_pp0_iter5_reg <= u_3_addr_reg_960_pp0_iter4_reg;
        u_3_addr_reg_960_pp0_iter6_reg <= u_3_addr_reg_960_pp0_iter5_reg;
        u_3_addr_reg_960_pp0_iter7_reg <= u_3_addr_reg_960_pp0_iter6_reg;
        u_3_addr_reg_960_pp0_iter8_reg <= u_3_addr_reg_960_pp0_iter7_reg;
        u_4_addr_reg_966_pp0_iter2_reg <= u_4_addr_reg_966_pp0_iter1_reg;
        u_4_addr_reg_966_pp0_iter3_reg <= u_4_addr_reg_966_pp0_iter2_reg;
        u_4_addr_reg_966_pp0_iter4_reg <= u_4_addr_reg_966_pp0_iter3_reg;
        u_4_addr_reg_966_pp0_iter5_reg <= u_4_addr_reg_966_pp0_iter4_reg;
        u_4_addr_reg_966_pp0_iter6_reg <= u_4_addr_reg_966_pp0_iter5_reg;
        u_4_addr_reg_966_pp0_iter7_reg <= u_4_addr_reg_966_pp0_iter6_reg;
        u_4_addr_reg_966_pp0_iter8_reg <= u_4_addr_reg_966_pp0_iter7_reg;
        u_5_addr_reg_972_pp0_iter2_reg <= u_5_addr_reg_972_pp0_iter1_reg;
        u_5_addr_reg_972_pp0_iter3_reg <= u_5_addr_reg_972_pp0_iter2_reg;
        u_5_addr_reg_972_pp0_iter4_reg <= u_5_addr_reg_972_pp0_iter3_reg;
        u_5_addr_reg_972_pp0_iter5_reg <= u_5_addr_reg_972_pp0_iter4_reg;
        u_5_addr_reg_972_pp0_iter6_reg <= u_5_addr_reg_972_pp0_iter5_reg;
        u_5_addr_reg_972_pp0_iter7_reg <= u_5_addr_reg_972_pp0_iter6_reg;
        u_5_addr_reg_972_pp0_iter8_reg <= u_5_addr_reg_972_pp0_iter7_reg;
        u_6_addr_reg_978_pp0_iter2_reg <= u_6_addr_reg_978_pp0_iter1_reg;
        u_6_addr_reg_978_pp0_iter3_reg <= u_6_addr_reg_978_pp0_iter2_reg;
        u_6_addr_reg_978_pp0_iter4_reg <= u_6_addr_reg_978_pp0_iter3_reg;
        u_6_addr_reg_978_pp0_iter5_reg <= u_6_addr_reg_978_pp0_iter4_reg;
        u_6_addr_reg_978_pp0_iter6_reg <= u_6_addr_reg_978_pp0_iter5_reg;
        u_6_addr_reg_978_pp0_iter7_reg <= u_6_addr_reg_978_pp0_iter6_reg;
        u_6_addr_reg_978_pp0_iter8_reg <= u_6_addr_reg_978_pp0_iter7_reg;
        u_7_addr_reg_984_pp0_iter2_reg <= u_7_addr_reg_984_pp0_iter1_reg;
        u_7_addr_reg_984_pp0_iter3_reg <= u_7_addr_reg_984_pp0_iter2_reg;
        u_7_addr_reg_984_pp0_iter4_reg <= u_7_addr_reg_984_pp0_iter3_reg;
        u_7_addr_reg_984_pp0_iter5_reg <= u_7_addr_reg_984_pp0_iter4_reg;
        u_7_addr_reg_984_pp0_iter6_reg <= u_7_addr_reg_984_pp0_iter5_reg;
        u_7_addr_reg_984_pp0_iter7_reg <= u_7_addr_reg_984_pp0_iter6_reg;
        u_7_addr_reg_984_pp0_iter8_reg <= u_7_addr_reg_984_pp0_iter7_reg;
        u_8_addr_reg_990_pp0_iter2_reg <= u_8_addr_reg_990_pp0_iter1_reg;
        u_8_addr_reg_990_pp0_iter3_reg <= u_8_addr_reg_990_pp0_iter2_reg;
        u_8_addr_reg_990_pp0_iter4_reg <= u_8_addr_reg_990_pp0_iter3_reg;
        u_8_addr_reg_990_pp0_iter5_reg <= u_8_addr_reg_990_pp0_iter4_reg;
        u_8_addr_reg_990_pp0_iter6_reg <= u_8_addr_reg_990_pp0_iter5_reg;
        u_8_addr_reg_990_pp0_iter7_reg <= u_8_addr_reg_990_pp0_iter6_reg;
        u_8_addr_reg_990_pp0_iter8_reg <= u_8_addr_reg_990_pp0_iter7_reg;
        u_9_addr_reg_996_pp0_iter2_reg <= u_9_addr_reg_996_pp0_iter1_reg;
        u_9_addr_reg_996_pp0_iter3_reg <= u_9_addr_reg_996_pp0_iter2_reg;
        u_9_addr_reg_996_pp0_iter4_reg <= u_9_addr_reg_996_pp0_iter3_reg;
        u_9_addr_reg_996_pp0_iter5_reg <= u_9_addr_reg_996_pp0_iter4_reg;
        u_9_addr_reg_996_pp0_iter6_reg <= u_9_addr_reg_996_pp0_iter5_reg;
        u_9_addr_reg_996_pp0_iter7_reg <= u_9_addr_reg_996_pp0_iter6_reg;
        u_9_addr_reg_996_pp0_iter8_reg <= u_9_addr_reg_996_pp0_iter7_reg;
        u_addr_reg_942_pp0_iter2_reg <= u_addr_reg_942_pp0_iter1_reg;
        u_addr_reg_942_pp0_iter3_reg <= u_addr_reg_942_pp0_iter2_reg;
        u_addr_reg_942_pp0_iter4_reg <= u_addr_reg_942_pp0_iter3_reg;
        u_addr_reg_942_pp0_iter5_reg <= u_addr_reg_942_pp0_iter4_reg;
        u_addr_reg_942_pp0_iter6_reg <= u_addr_reg_942_pp0_iter5_reg;
        u_addr_reg_942_pp0_iter7_reg <= u_addr_reg_942_pp0_iter6_reg;
        u_addr_reg_942_pp0_iter8_reg <= u_addr_reg_942_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_4_reg_1043 <= tmp_4_fu_774_p35;
        tmp_s_reg_1038 <= tmp_s_fu_703_p35;
        trunc_ln671_reg_856 <= trunc_ln671_fu_648_p1;
        trunc_ln671_reg_856_pp0_iter1_reg <= trunc_ln671_reg_856;
        u_10_addr_reg_1002 <= zext_ln671_fu_662_p1;
        u_10_addr_reg_1002_pp0_iter1_reg <= u_10_addr_reg_1002;
        u_11_addr_reg_1008 <= zext_ln671_fu_662_p1;
        u_11_addr_reg_1008_pp0_iter1_reg <= u_11_addr_reg_1008;
        u_12_addr_reg_1014 <= zext_ln671_fu_662_p1;
        u_12_addr_reg_1014_pp0_iter1_reg <= u_12_addr_reg_1014;
        u_13_addr_reg_1020 <= zext_ln671_fu_662_p1;
        u_13_addr_reg_1020_pp0_iter1_reg <= u_13_addr_reg_1020;
        u_14_addr_reg_1026 <= zext_ln671_fu_662_p1;
        u_14_addr_reg_1026_pp0_iter1_reg <= u_14_addr_reg_1026;
        u_15_addr_reg_1032 <= zext_ln671_fu_662_p1;
        u_15_addr_reg_1032_pp0_iter1_reg <= u_15_addr_reg_1032;
        u_1_addr_reg_948 <= zext_ln671_fu_662_p1;
        u_1_addr_reg_948_pp0_iter1_reg <= u_1_addr_reg_948;
        u_2_addr_reg_954 <= zext_ln671_fu_662_p1;
        u_2_addr_reg_954_pp0_iter1_reg <= u_2_addr_reg_954;
        u_3_addr_reg_960 <= zext_ln671_fu_662_p1;
        u_3_addr_reg_960_pp0_iter1_reg <= u_3_addr_reg_960;
        u_4_addr_reg_966 <= zext_ln671_fu_662_p1;
        u_4_addr_reg_966_pp0_iter1_reg <= u_4_addr_reg_966;
        u_5_addr_reg_972 <= zext_ln671_fu_662_p1;
        u_5_addr_reg_972_pp0_iter1_reg <= u_5_addr_reg_972;
        u_6_addr_reg_978 <= zext_ln671_fu_662_p1;
        u_6_addr_reg_978_pp0_iter1_reg <= u_6_addr_reg_978;
        u_7_addr_reg_984 <= zext_ln671_fu_662_p1;
        u_7_addr_reg_984_pp0_iter1_reg <= u_7_addr_reg_984;
        u_8_addr_reg_990 <= zext_ln671_fu_662_p1;
        u_8_addr_reg_990_pp0_iter1_reg <= u_8_addr_reg_990;
        u_9_addr_reg_996 <= zext_ln671_fu_662_p1;
        u_9_addr_reg_996_pp0_iter1_reg <= u_9_addr_reg_996;
        u_addr_reg_942 <= zext_ln671_fu_662_p1;
        u_addr_reg_942_pp0_iter1_reg <= u_addr_reg_942;
    end
end

always @ (*) begin
    if (((icmp_ln671_fu_636_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_10_ce0 = 1'b1;
    end else begin
        u_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_10_ce1 = 1'b1;
    end else begin
        u_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd10))) begin
        u_10_we0 = 1'b1;
    end else begin
        u_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_11_ce0 = 1'b1;
    end else begin
        u_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_11_ce1 = 1'b1;
    end else begin
        u_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd11))) begin
        u_11_we0 = 1'b1;
    end else begin
        u_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_12_ce0 = 1'b1;
    end else begin
        u_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_12_ce1 = 1'b1;
    end else begin
        u_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd12))) begin
        u_12_we0 = 1'b1;
    end else begin
        u_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_13_ce0 = 1'b1;
    end else begin
        u_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_13_ce1 = 1'b1;
    end else begin
        u_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd13))) begin
        u_13_we0 = 1'b1;
    end else begin
        u_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_14_ce0 = 1'b1;
    end else begin
        u_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_14_ce1 = 1'b1;
    end else begin
        u_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd14))) begin
        u_14_we0 = 1'b1;
    end else begin
        u_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_15_ce0 = 1'b1;
    end else begin
        u_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_15_ce1 = 1'b1;
    end else begin
        u_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd15))) begin
        u_15_we0 = 1'b1;
    end else begin
        u_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_1_ce0 = 1'b1;
    end else begin
        u_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_1_ce1 = 1'b1;
    end else begin
        u_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd1))) begin
        u_1_we0 = 1'b1;
    end else begin
        u_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_2_ce0 = 1'b1;
    end else begin
        u_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_2_ce1 = 1'b1;
    end else begin
        u_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd2))) begin
        u_2_we0 = 1'b1;
    end else begin
        u_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_3_ce0 = 1'b1;
    end else begin
        u_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_3_ce1 = 1'b1;
    end else begin
        u_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd3))) begin
        u_3_we0 = 1'b1;
    end else begin
        u_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_4_ce0 = 1'b1;
    end else begin
        u_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_4_ce1 = 1'b1;
    end else begin
        u_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd4))) begin
        u_4_we0 = 1'b1;
    end else begin
        u_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_5_ce0 = 1'b1;
    end else begin
        u_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_5_ce1 = 1'b1;
    end else begin
        u_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd5))) begin
        u_5_we0 = 1'b1;
    end else begin
        u_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_6_ce0 = 1'b1;
    end else begin
        u_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_6_ce1 = 1'b1;
    end else begin
        u_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd6))) begin
        u_6_we0 = 1'b1;
    end else begin
        u_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_7_ce0 = 1'b1;
    end else begin
        u_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_7_ce1 = 1'b1;
    end else begin
        u_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd7))) begin
        u_7_we0 = 1'b1;
    end else begin
        u_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_8_ce0 = 1'b1;
    end else begin
        u_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_8_ce1 = 1'b1;
    end else begin
        u_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd8))) begin
        u_8_we0 = 1'b1;
    end else begin
        u_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_9_ce0 = 1'b1;
    end else begin
        u_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_9_ce1 = 1'b1;
    end else begin
        u_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd9))) begin
        u_9_we0 = 1'b1;
    end else begin
        u_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        u_ce0 = 1'b1;
    end else begin
        u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        u_ce1 = 1'b1;
    end else begin
        u_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln671_reg_856_pp0_iter8_reg == 4'd0))) begin
        u_we0 = 1'b1;
    end else begin
        u_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_10_ce0 = 1'b1;
    end else begin
        x_hat_z_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_11_ce0 = 1'b1;
    end else begin
        x_hat_z_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_12_ce0 = 1'b1;
    end else begin
        x_hat_z_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_13_ce0 = 1'b1;
    end else begin
        x_hat_z_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_14_ce0 = 1'b1;
    end else begin
        x_hat_z_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_15_ce0 = 1'b1;
    end else begin
        x_hat_z_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_1_ce0 = 1'b1;
    end else begin
        x_hat_z_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_2_ce0 = 1'b1;
    end else begin
        x_hat_z_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_3_ce0 = 1'b1;
    end else begin
        x_hat_z_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_4_ce0 = 1'b1;
    end else begin
        x_hat_z_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_5_ce0 = 1'b1;
    end else begin
        x_hat_z_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_6_ce0 = 1'b1;
    end else begin
        x_hat_z_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_7_ce0 = 1'b1;
    end else begin
        x_hat_z_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_8_ce0 = 1'b1;
    end else begin
        x_hat_z_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_9_ce0 = 1'b1;
    end else begin
        x_hat_z_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_hat_z_ce0 = 1'b1;
    end else begin
        x_hat_z_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln671_fu_642_p2 = (ap_sig_allocacmp_i_2 + 31'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1657_p_ce = 1'b1;

assign grp_fu_1657_p_din0 = tmp_4_reg_1043;

assign grp_fu_1657_p_din1 = tmp_s_reg_1038;

assign grp_fu_1657_p_opcode = 2'd0;

assign icmp_ln671_fu_636_p2 = ((ap_sig_allocacmp_i_2 == chunk) ? 1'b1 : 1'b0);

assign lshr_ln_fu_652_p4 = {{ap_sig_allocacmp_i_2[6:4]}};

assign tmp_4_fu_774_p33 = 'bx;

assign tmp_s_fu_703_p33 = 'bx;

assign trunc_ln671_fu_648_p1 = ap_sig_allocacmp_i_2[3:0];

assign u_10_address0 = u_10_addr_reg_1002_pp0_iter8_reg;

assign u_10_address1 = zext_ln671_fu_662_p1;

assign u_10_d0 = add4_reg_1048;

assign u_11_address0 = u_11_addr_reg_1008_pp0_iter8_reg;

assign u_11_address1 = zext_ln671_fu_662_p1;

assign u_11_d0 = add4_reg_1048;

assign u_12_address0 = u_12_addr_reg_1014_pp0_iter8_reg;

assign u_12_address1 = zext_ln671_fu_662_p1;

assign u_12_d0 = add4_reg_1048;

assign u_13_address0 = u_13_addr_reg_1020_pp0_iter8_reg;

assign u_13_address1 = zext_ln671_fu_662_p1;

assign u_13_d0 = add4_reg_1048;

assign u_14_address0 = u_14_addr_reg_1026_pp0_iter8_reg;

assign u_14_address1 = zext_ln671_fu_662_p1;

assign u_14_d0 = add4_reg_1048;

assign u_15_address0 = u_15_addr_reg_1032_pp0_iter8_reg;

assign u_15_address1 = zext_ln671_fu_662_p1;

assign u_15_d0 = add4_reg_1048;

assign u_1_address0 = u_1_addr_reg_948_pp0_iter8_reg;

assign u_1_address1 = zext_ln671_fu_662_p1;

assign u_1_d0 = add4_reg_1048;

assign u_2_address0 = u_2_addr_reg_954_pp0_iter8_reg;

assign u_2_address1 = zext_ln671_fu_662_p1;

assign u_2_d0 = add4_reg_1048;

assign u_3_address0 = u_3_addr_reg_960_pp0_iter8_reg;

assign u_3_address1 = zext_ln671_fu_662_p1;

assign u_3_d0 = add4_reg_1048;

assign u_4_address0 = u_4_addr_reg_966_pp0_iter8_reg;

assign u_4_address1 = zext_ln671_fu_662_p1;

assign u_4_d0 = add4_reg_1048;

assign u_5_address0 = u_5_addr_reg_972_pp0_iter8_reg;

assign u_5_address1 = zext_ln671_fu_662_p1;

assign u_5_d0 = add4_reg_1048;

assign u_6_address0 = u_6_addr_reg_978_pp0_iter8_reg;

assign u_6_address1 = zext_ln671_fu_662_p1;

assign u_6_d0 = add4_reg_1048;

assign u_7_address0 = u_7_addr_reg_984_pp0_iter8_reg;

assign u_7_address1 = zext_ln671_fu_662_p1;

assign u_7_d0 = add4_reg_1048;

assign u_8_address0 = u_8_addr_reg_990_pp0_iter8_reg;

assign u_8_address1 = zext_ln671_fu_662_p1;

assign u_8_d0 = add4_reg_1048;

assign u_9_address0 = u_9_addr_reg_996_pp0_iter8_reg;

assign u_9_address1 = zext_ln671_fu_662_p1;

assign u_9_d0 = add4_reg_1048;

assign u_address0 = u_addr_reg_942_pp0_iter8_reg;

assign u_address1 = zext_ln671_fu_662_p1;

assign u_d0 = add4_reg_1048;

assign x_hat_z_10_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_11_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_12_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_13_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_14_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_15_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_1_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_2_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_3_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_4_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_5_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_6_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_7_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_8_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_9_address0 = zext_ln671_fu_662_p1;

assign x_hat_z_address0 = zext_ln671_fu_662_p1;

assign zext_ln671_fu_662_p1 = lshr_ln_fu_652_p4;

endmodule //krnl_bp_krnl_bp_Pipeline_VITIS_LOOP_671_11
