-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_bp_mac is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_p_bram_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_p_bram_ce0 : OUT STD_LOGIC;
    mat_p_bram_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_u_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    z_u_stream_empty_n : IN STD_LOGIC;
    z_u_stream_read : OUT STD_LOGIC;
    mac_res_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mac_res_stream_full_n : IN STD_LOGIC;
    mac_res_stream_write : OUT STD_LOGIC;
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC;
    grp_fu_626_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_626_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_626_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_626_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_626_p_ce : OUT STD_LOGIC;
    grp_fu_631_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_631_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_631_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_631_p_ce : OUT STD_LOGIC );
end;


architecture behav of krnl_bp_mac is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mac_res_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_s_nbwritereq_fu_68_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ii_4_fu_120_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ii_4_reg_154 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal z_u_local_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_u_local_ce0 : STD_LOGIC;
    signal z_u_local_we0 : STD_LOGIC;
    signal z_u_local_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_idle : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0 : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_idle : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0 : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0 : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_idle : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0 : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out_ap_vld : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_stream_full_n : STD_LOGIC;
    signal p_stream_write : STD_LOGIC;
    signal grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln256_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal p_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal p_stream_empty_n : STD_LOGIC;
    signal p_stream_read : STD_LOGIC;
    signal ii_3_fu_56 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state9 : BOOLEAN;
    signal grp_fu_162_ce : STD_LOGIC;
    signal grp_fu_166_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ext_blocking_sub_n : STD_LOGIC;
    signal ap_wait_0 : STD_LOGIC;
    signal ap_sub_ext_blocking_0 : STD_LOGIC;
    signal ap_wait_1 : STD_LOGIC;
    signal ap_sub_ext_blocking_1 : STD_LOGIC;
    signal ap_wait_2 : STD_LOGIC;
    signal ap_sub_ext_blocking_2 : STD_LOGIC;
    signal ap_str_blocking_sub_n : STD_LOGIC;
    signal ap_sub_str_blocking_0 : STD_LOGIC;
    signal ap_sub_str_blocking_1 : STD_LOGIC;
    signal ap_sub_str_blocking_2 : STD_LOGIC;
    signal ap_int_blocking_sub_n : STD_LOGIC;
    signal ap_sub_int_blocking_0 : STD_LOGIC;
    signal ap_sub_int_blocking_1 : STD_LOGIC;
    signal ap_sub_int_blocking_2 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_bp_mac_Pipeline_VITIS_LOOP_234_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_stream_full_n : IN STD_LOGIC;
        p_stream_write : OUT STD_LOGIC;
        mat_p_bram_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        mat_p_bram_ce0 : OUT STD_LOGIC;
        mat_p_bram_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component krnl_bp_mac_Pipeline_VITIS_LOOP_242_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        z_u_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        z_u_stream_empty_n : IN STD_LOGIC;
        z_u_stream_read : OUT STD_LOGIC;
        z_u_local_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        z_u_local_ce0 : OUT STD_LOGIC;
        z_u_local_we0 : OUT STD_LOGIC;
        z_u_local_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component krnl_bp_mac_Pipeline_VITIS_LOOP_259_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        z_u_local_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        z_u_local_ce0 : OUT STD_LOGIC;
        z_u_local_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        result_tmp_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        result_tmp_out_ap_vld : OUT STD_LOGIC;
        p_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_stream_empty_n : IN STD_LOGIC;
        p_stream_read : OUT STD_LOGIC;
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC;
        grp_fu_162_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_162_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_162_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_162_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_162_p_ce : OUT STD_LOGIC;
        grp_fu_166_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_166_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_166_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_166_p_ce : OUT STD_LOGIC );
    end component;


    component krnl_bp_faddfsub_32ns_32ns_32_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_bp_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_bp_mac_z_u_local_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_bp_fifo_w32_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    z_u_local_U : component krnl_bp_mac_z_u_local_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => z_u_local_address0,
        ce0 => z_u_local_ce0,
        we0 => z_u_local_we0,
        d0 => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0,
        q0 => z_u_local_q0);

    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83 : component krnl_bp_mac_Pipeline_VITIS_LOOP_234_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start,
        ap_done => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done,
        ap_idle => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_idle,
        ap_ready => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready,
        p_stream_din => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din,
        p_stream_full_n => p_stream_full_n,
        p_stream_write => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write,
        mat_p_bram_address0 => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0,
        mat_p_bram_ce0 => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0,
        mat_p_bram_q0 => mat_p_bram_q0,
        ap_ext_blocking_n => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n,
        ap_str_blocking_n => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n,
        ap_int_blocking_n => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n);

    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91 : component krnl_bp_mac_Pipeline_VITIS_LOOP_242_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start,
        ap_done => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done,
        ap_idle => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_idle,
        ap_ready => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready,
        z_u_stream_dout => z_u_stream_dout,
        z_u_stream_empty_n => z_u_stream_empty_n,
        z_u_stream_read => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read,
        z_u_local_address0 => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0,
        z_u_local_ce0 => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0,
        z_u_local_we0 => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0,
        z_u_local_d0 => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0,
        ap_ext_blocking_n => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n,
        ap_str_blocking_n => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n,
        ap_int_blocking_n => grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n);

    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98 : component krnl_bp_mac_Pipeline_VITIS_LOOP_259_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start,
        ap_done => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done,
        ap_idle => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_idle,
        ap_ready => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready,
        z_u_local_address0 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0,
        z_u_local_ce0 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0,
        z_u_local_q0 => z_u_local_q0,
        result_tmp_out => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out,
        result_tmp_out_ap_vld => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out_ap_vld,
        p_stream_dout => p_stream_dout,
        p_stream_empty_n => p_stream_empty_n,
        p_stream_read => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read,
        ap_ext_blocking_n => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n,
        ap_str_blocking_n => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n,
        ap_int_blocking_n => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n,
        grp_fu_162_p_din0 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0,
        grp_fu_162_p_din1 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1,
        grp_fu_162_p_opcode => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode,
        grp_fu_162_p_dout0 => grp_fu_626_p_dout0,
        grp_fu_162_p_ce => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce,
        grp_fu_166_p_din0 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0,
        grp_fu_166_p_din1 => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1,
        grp_fu_166_p_dout0 => grp_fu_631_p_dout0,
        grp_fu_166_p_ce => grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce);

    p_stream_fifo_U : component krnl_bp_fifo_w32_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din,
        if_full_n => p_stream_full_n,
        if_write => p_stream_write,
        if_dout => p_stream_dout,
        if_empty_n => p_stream_empty_n,
        if_read => p_stream_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready = ap_const_logic_1)) then 
                    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready = ap_const_logic_1)) then 
                    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln256_fu_114_p2 = ap_const_lv1_0))) then 
                    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ii_3_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ii_3_fu_56 <= ap_const_lv4_0;
            elsif ((not(((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (mac_res_stream_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                ii_3_fu_56 <= ii_4_reg_154;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                ii_4_reg_154 <= ii_4_fu_120_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, mac_res_stream_full_n, ap_CS_fsm_state9, tmp_s_nbwritereq_fu_68_p3, ap_CS_fsm_state7, grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done, grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done, grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state5, icmp_ln256_fu_114_p2, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln256_fu_114_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (mac_res_stream_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(mac_res_stream_full_n, tmp_s_nbwritereq_fu_68_p3)
    begin
        if (((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (mac_res_stream_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state9_assign_proc : process(mac_res_stream_full_n, tmp_s_nbwritereq_fu_68_p3)
    begin
                ap_block_state9 <= ((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (mac_res_stream_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7, icmp_ln256_fu_114_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln256_fu_114_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_ext_blocking_n <= (ap_ext_blocking_sub_n and ap_const_logic_1);

    ap_ext_blocking_sub_n_assign_proc : process(ap_wait_0, ap_sub_ext_blocking_0, ap_wait_1, ap_sub_ext_blocking_1, ap_wait_2, ap_sub_ext_blocking_2)
    begin
        if ((((ap_wait_2 and ap_sub_ext_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_ext_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_ext_blocking_0) = ap_const_logic_1))) then 
            ap_ext_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_ext_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_n <= (ap_int_blocking_sub_n and ap_const_logic_1);

    ap_int_blocking_sub_n_assign_proc : process(ap_wait_0, ap_wait_1, ap_wait_2, ap_sub_int_blocking_0, ap_sub_int_blocking_1, ap_sub_int_blocking_2)
    begin
        if ((((ap_wait_2 and ap_sub_int_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_int_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_int_blocking_0) = ap_const_logic_1))) then 
            ap_int_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_int_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, icmp_ln256_fu_114_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln256_fu_114_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_str_blocking_sub_n and ap_const_logic_1);

    ap_str_blocking_sub_n_assign_proc : process(ap_wait_0, ap_wait_1, ap_wait_2, ap_sub_str_blocking_0, ap_sub_str_blocking_1, ap_sub_str_blocking_2)
    begin
        if ((((ap_wait_2 and ap_sub_str_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_str_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_str_blocking_0) = ap_const_logic_1))) then 
            ap_str_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_str_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_sub_ext_blocking_0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_ext_blocking_1_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_ext_blocking_2_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_1_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_2_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_1_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_2_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n)
    begin
        if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_0_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state2 = ap_CS_fsm)) then 
            ap_wait_0 <= ap_const_logic_1;
        else 
            ap_wait_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_1_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state5 = ap_CS_fsm)) then 
            ap_wait_1 <= ap_const_logic_1;
        else 
            ap_wait_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_2_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state8 = ap_CS_fsm)) then 
            ap_wait_2 <= ap_const_logic_1;
        else 
            ap_wait_2 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_162_ce_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_162_ce <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce;
        else 
            grp_fu_162_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_166_ce_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_166_ce <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce;
        else 
            grp_fu_166_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_626_p_ce <= grp_fu_162_ce;
    grp_fu_626_p_din0 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0;
    grp_fu_626_p_din1 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1;
    grp_fu_626_p_opcode <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode;
    grp_fu_631_p_ce <= grp_fu_166_ce;
    grp_fu_631_p_din0 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0;
    grp_fu_631_p_din1 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1;
    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start <= grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg;
    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start <= grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg;
    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg;
    icmp_ln256_fu_114_p2 <= "1" when (ii_3_fu_56 = ap_const_lv4_8) else "0";
    ii_4_fu_120_p2 <= std_logic_vector(unsigned(ii_3_fu_56) + unsigned(ap_const_lv4_1));

    mac_res_stream_blk_n_assign_proc : process(mac_res_stream_full_n, ap_CS_fsm_state9, tmp_s_nbwritereq_fu_68_p3)
    begin
        if (((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            mac_res_stream_blk_n <= mac_res_stream_full_n;
        else 
            mac_res_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mac_res_stream_din <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out;

    mac_res_stream_write_assign_proc : process(mac_res_stream_full_n, ap_CS_fsm_state9, tmp_s_nbwritereq_fu_68_p3)
    begin
        if ((not(((tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (mac_res_stream_full_n = ap_const_logic_0))) and (tmp_s_nbwritereq_fu_68_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            mac_res_stream_write <= ap_const_logic_1;
        else 
            mac_res_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    mat_p_bram_address0 <= grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0;
    mat_p_bram_ce0 <= grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0;

    p_stream_read_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            p_stream_read <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read;
        else 
            p_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    p_stream_write_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_stream_write <= grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write;
        else 
            p_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_nbwritereq_fu_68_p3 <= (0=>mac_res_stream_full_n, others=>'-');

    z_u_local_address0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0, grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0, ap_CS_fsm_state5, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            z_u_local_address0 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            z_u_local_address0 <= grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0;
        else 
            z_u_local_address0 <= "XXX";
        end if; 
    end process;


    z_u_local_ce0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0, grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0, ap_CS_fsm_state5, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            z_u_local_ce0 <= grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            z_u_local_ce0 <= grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0;
        else 
            z_u_local_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    z_u_local_we0_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            z_u_local_we0 <= grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0;
        else 
            z_u_local_we0 <= ap_const_logic_0;
        end if; 
    end process;


    z_u_stream_read_assign_proc : process(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            z_u_stream_read <= grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read;
        else 
            z_u_stream_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
