// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_bp_replicate_stream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        krnl_bp_u_stream_dout,
        krnl_bp_u_stream_empty_n,
        krnl_bp_u_stream_read,
        krnl_bp_u_copy_1_stream_din,
        krnl_bp_u_copy_1_stream_full_n,
        krnl_bp_u_copy_1_stream_write,
        krnl_bp_u_copy_2_stream_din,
        krnl_bp_u_copy_2_stream_full_n,
        krnl_bp_u_copy_2_stream_write,
        krnl_bp_u_copy_3_stream_din,
        krnl_bp_u_copy_3_stream_full_n,
        krnl_bp_u_copy_3_stream_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] krnl_bp_u_stream_dout;
input   krnl_bp_u_stream_empty_n;
output   krnl_bp_u_stream_read;
output  [31:0] krnl_bp_u_copy_1_stream_din;
input   krnl_bp_u_copy_1_stream_full_n;
output   krnl_bp_u_copy_1_stream_write;
output  [31:0] krnl_bp_u_copy_2_stream_din;
input   krnl_bp_u_copy_2_stream_full_n;
output   krnl_bp_u_copy_2_stream_write;
output  [31:0] krnl_bp_u_copy_3_stream_din;
input   krnl_bp_u_copy_3_stream_full_n;
output   krnl_bp_u_copy_3_stream_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_idle;
reg krnl_bp_u_stream_read;
reg krnl_bp_u_copy_1_stream_write;
reg krnl_bp_u_copy_2_stream_write;
reg krnl_bp_u_copy_3_stream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_nbreadreq_fu_46_p3;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] tmp_reg_117;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln653_fu_89_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    krnl_bp_u_stream_blk_n;
wire    ap_block_pp0_stage0;
reg    krnl_bp_u_copy_1_stream_blk_n;
reg    krnl_bp_u_copy_2_stream_blk_n;
reg    krnl_bp_u_copy_3_stream_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] val_reg_121;
reg   [3:0] ii_fu_42;
wire   [3:0] ii_2_fu_95_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_ii_1;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

krnl_bp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln653_fu_89_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ii_fu_42 <= ii_2_fu_95_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ii_fu_42 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_reg_117 <= tmp_nbreadreq_fu_46_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_46_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        val_reg_121 <= krnl_bp_u_stream_dout;
    end
end

always @ (*) begin
    if (((icmp_ln653_fu_89_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ii_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_ii_1 = ii_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_1_stream_blk_n = krnl_bp_u_copy_1_stream_full_n;
    end else begin
        krnl_bp_u_copy_1_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_1_stream_write = 1'b1;
    end else begin
        krnl_bp_u_copy_1_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_2_stream_blk_n = krnl_bp_u_copy_2_stream_full_n;
    end else begin
        krnl_bp_u_copy_2_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_2_stream_write = 1'b1;
    end else begin
        krnl_bp_u_copy_2_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_3_stream_blk_n = krnl_bp_u_copy_3_stream_full_n;
    end else begin
        krnl_bp_u_copy_3_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_117 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        krnl_bp_u_copy_3_stream_write = 1'b1;
    end else begin
        krnl_bp_u_copy_3_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_nbreadreq_fu_46_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        krnl_bp_u_stream_blk_n = krnl_bp_u_stream_empty_n;
    end else begin
        krnl_bp_u_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_46_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        krnl_bp_u_stream_read = 1'b1;
    end else begin
        krnl_bp_u_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((krnl_bp_u_copy_3_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((krnl_bp_u_copy_2_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((tmp_reg_117 == 1'd1) & (krnl_bp_u_copy_1_stream_full_n == 1'b0)))) | ((tmp_nbreadreq_fu_46_p3 == 1'd1) & (krnl_bp_u_stream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((krnl_bp_u_copy_3_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((krnl_bp_u_copy_2_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((tmp_reg_117 == 1'd1) & (krnl_bp_u_copy_1_stream_full_n == 1'b0)))) | ((tmp_nbreadreq_fu_46_p3 == 1'd1) & (krnl_bp_u_stream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((krnl_bp_u_copy_3_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((krnl_bp_u_copy_2_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((tmp_reg_117 == 1'd1) & (krnl_bp_u_copy_1_stream_full_n == 1'b0)))) | ((tmp_nbreadreq_fu_46_p3 == 1'd1) & (krnl_bp_u_stream_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((tmp_nbreadreq_fu_46_p3 == 1'd1) & (krnl_bp_u_stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((krnl_bp_u_copy_3_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((krnl_bp_u_copy_2_stream_full_n == 1'b0) & (tmp_reg_117 == 1'd1)) | ((tmp_reg_117 == 1'd1) & (krnl_bp_u_copy_1_stream_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign icmp_ln653_fu_89_p2 = ((ap_sig_allocacmp_ii_1 == 4'd8) ? 1'b1 : 1'b0);

assign ii_2_fu_95_p2 = (ap_sig_allocacmp_ii_1 + 4'd1);

assign krnl_bp_u_copy_1_stream_din = val_reg_121;

assign krnl_bp_u_copy_2_stream_din = val_reg_121;

assign krnl_bp_u_copy_3_stream_din = val_reg_121;

assign tmp_nbreadreq_fu_46_p3 = krnl_bp_u_stream_empty_n;

endmodule //krnl_bp_replicate_stream
