// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_bp_mac (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_p_bram_address0,
        mat_p_bram_ce0,
        mat_p_bram_q0,
        z_u_stream_dout,
        z_u_stream_empty_n,
        z_u_stream_read,
        mac_res_stream_din,
        mac_res_stream_full_n,
        mac_res_stream_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n,
        grp_fu_626_p_din0,
        grp_fu_626_p_din1,
        grp_fu_626_p_opcode,
        grp_fu_626_p_dout0,
        grp_fu_626_p_ce,
        grp_fu_631_p_din0,
        grp_fu_631_p_din1,
        grp_fu_631_p_dout0,
        grp_fu_631_p_ce
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] mat_p_bram_address0;
output   mat_p_bram_ce0;
input  [31:0] mat_p_bram_q0;
input  [31:0] z_u_stream_dout;
input   z_u_stream_empty_n;
output   z_u_stream_read;
output  [31:0] mac_res_stream_din;
input   mac_res_stream_full_n;
output   mac_res_stream_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;
output  [31:0] grp_fu_626_p_din0;
output  [31:0] grp_fu_626_p_din1;
output  [0:0] grp_fu_626_p_opcode;
input  [31:0] grp_fu_626_p_dout0;
output   grp_fu_626_p_ce;
output  [31:0] grp_fu_631_p_din0;
output  [31:0] grp_fu_631_p_din1;
input  [31:0] grp_fu_631_p_dout0;
output   grp_fu_631_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg z_u_stream_read;
reg mac_res_stream_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mac_res_stream_blk_n;
wire    ap_CS_fsm_state9;
wire   [0:0] tmp_s_nbwritereq_fu_68_p3;
wire   [3:0] ii_4_fu_120_p2;
reg   [3:0] ii_4_reg_154;
wire    ap_CS_fsm_state7;
reg   [2:0] z_u_local_address0;
reg    z_u_local_ce0;
reg    z_u_local_we0;
wire   [31:0] z_u_local_q0;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_idle;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write;
wire   [5:0] grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_idle;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read;
wire   [2:0] grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_idle;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready;
wire   [2:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out_ap_vld;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1;
wire   [0:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0;
wire   [31:0] grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1;
wire    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce;
reg    grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    p_stream_full_n;
reg    p_stream_write;
reg    grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg;
wire   [0:0] icmp_ln256_fu_114_p2;
wire    ap_CS_fsm_state8;
wire   [31:0] p_stream_dout;
wire    p_stream_empty_n;
reg    p_stream_read;
reg   [3:0] ii_3_fu_56;
reg    ap_block_state9;
reg    grp_fu_162_ce;
reg    grp_fu_166_ce;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_wait_1;
reg    ap_sub_ext_blocking_1;
reg    ap_wait_2;
reg    ap_sub_ext_blocking_2;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_sub_str_blocking_1;
reg    ap_sub_str_blocking_2;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
reg    ap_sub_int_blocking_1;
reg    ap_sub_int_blocking_2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg = 1'b0;
#0 grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg = 1'b0;
#0 grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg = 1'b0;
end

krnl_bp_mac_z_u_local_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
z_u_local_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z_u_local_address0),
    .ce0(z_u_local_ce0),
    .we0(z_u_local_we0),
    .d0(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0),
    .q0(z_u_local_q0)
);

krnl_bp_mac_Pipeline_VITIS_LOOP_234_1 grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start),
    .ap_done(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done),
    .ap_idle(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_idle),
    .ap_ready(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready),
    .p_stream_din(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din),
    .p_stream_full_n(p_stream_full_n),
    .p_stream_write(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write),
    .mat_p_bram_address0(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0),
    .mat_p_bram_ce0(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0),
    .mat_p_bram_q0(mat_p_bram_q0),
    .ap_ext_blocking_n(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n),
    .ap_int_blocking_n(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n)
);

krnl_bp_mac_Pipeline_VITIS_LOOP_242_2 grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start),
    .ap_done(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done),
    .ap_idle(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_idle),
    .ap_ready(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready),
    .z_u_stream_dout(z_u_stream_dout),
    .z_u_stream_empty_n(z_u_stream_empty_n),
    .z_u_stream_read(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read),
    .z_u_local_address0(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0),
    .z_u_local_ce0(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0),
    .z_u_local_we0(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0),
    .z_u_local_d0(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_d0),
    .ap_ext_blocking_n(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n),
    .ap_int_blocking_n(grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n)
);

krnl_bp_mac_Pipeline_VITIS_LOOP_259_4 grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start),
    .ap_done(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done),
    .ap_idle(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_idle),
    .ap_ready(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready),
    .z_u_local_address0(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0),
    .z_u_local_ce0(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0),
    .z_u_local_q0(z_u_local_q0),
    .result_tmp_out(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out),
    .result_tmp_out_ap_vld(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out_ap_vld),
    .p_stream_dout(p_stream_dout),
    .p_stream_empty_n(p_stream_empty_n),
    .p_stream_read(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read),
    .ap_ext_blocking_n(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n),
    .ap_int_blocking_n(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n),
    .grp_fu_162_p_din0(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0),
    .grp_fu_162_p_din1(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1),
    .grp_fu_162_p_opcode(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode),
    .grp_fu_162_p_dout0(grp_fu_626_p_dout0),
    .grp_fu_162_p_ce(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce),
    .grp_fu_166_p_din0(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1),
    .grp_fu_166_p_dout0(grp_fu_631_p_dout0),
    .grp_fu_166_p_ce(grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce)
);

krnl_bp_fifo_w32_d256_A p_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_din),
    .if_full_n(p_stream_full_n),
    .if_write(p_stream_write),
    .if_dout(p_stream_dout),
    .if_empty_n(p_stream_empty_n),
    .if_read(p_stream_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ready == 1'b1)) begin
            grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= 1'b1;
        end else if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ready == 1'b1)) begin
            grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln256_fu_114_p2 == 1'd0))) begin
            grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ready == 1'b1)) begin
            grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ii_3_fu_56 <= 4'd0;
    end else if ((~((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (mac_res_stream_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        ii_3_fu_56 <= ii_4_reg_154;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ii_4_reg_154 <= ii_4_fu_120_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (mac_res_stream_full_n == 1'b0))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state7) & (icmp_ln256_fu_114_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_2 & ap_sub_ext_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_ext_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1))) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_2 & ap_sub_int_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_int_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1))) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln256_fu_114_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_2 & ap_sub_str_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_str_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1))) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_1 = 1'b1;
    end else begin
        ap_sub_ext_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_2 = 1'b1;
    end else begin
        ap_sub_ext_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_1 = 1'b1;
    end else begin
        ap_sub_int_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_2 = 1'b1;
    end else begin
        ap_sub_int_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_1 = 1'b1;
    end else begin
        ap_sub_str_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_2 = 1'b1;
    end else begin
        ap_sub_str_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state2 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state5 == ap_CS_fsm)) begin
        ap_wait_1 = 1'b1;
    end else begin
        ap_wait_1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state8 == ap_CS_fsm)) begin
        ap_wait_2 = 1'b1;
    end else begin
        ap_wait_2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_162_ce = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_ce;
    end else begin
        grp_fu_162_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_166_ce = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_ce;
    end else begin
        grp_fu_166_ce = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        mac_res_stream_blk_n = mac_res_stream_full_n;
    end else begin
        mac_res_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (mac_res_stream_full_n == 1'b0)) & (tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        mac_res_stream_write = 1'b1;
    end else begin
        mac_res_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_stream_read = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_p_stream_read;
    end else begin
        p_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_stream_write = grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_p_stream_write;
    end else begin
        p_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        z_u_local_address0 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        z_u_local_address0 = grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_address0;
    end else begin
        z_u_local_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        z_u_local_ce0 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_z_u_local_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        z_u_local_ce0 = grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_ce0;
    end else begin
        z_u_local_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        z_u_local_we0 = grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_local_we0;
    end else begin
        z_u_local_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        z_u_stream_read = grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_z_u_stream_read;
    end else begin
        z_u_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln256_fu_114_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (mac_res_stream_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state9 = ((tmp_s_nbwritereq_fu_68_p3 == 1'd1) & (mac_res_stream_full_n == 1'b0));
end

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & 1'b1);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign grp_fu_626_p_ce = grp_fu_162_ce;

assign grp_fu_626_p_din0 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din0;

assign grp_fu_626_p_din1 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_din1;

assign grp_fu_626_p_opcode = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_162_p_opcode;

assign grp_fu_631_p_ce = grp_fu_166_ce;

assign grp_fu_631_p_din0 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din0;

assign grp_fu_631_p_din1 = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_grp_fu_166_p_din1;

assign grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start = grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_ap_start_reg;

assign grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start = grp_mac_Pipeline_VITIS_LOOP_242_2_fu_91_ap_start_reg;

assign grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_ap_start_reg;

assign icmp_ln256_fu_114_p2 = ((ii_3_fu_56 == 4'd8) ? 1'b1 : 1'b0);

assign ii_4_fu_120_p2 = (ii_3_fu_56 + 4'd1);

assign mac_res_stream_din = grp_mac_Pipeline_VITIS_LOOP_259_4_fu_98_result_tmp_out;

assign mat_p_bram_address0 = grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_address0;

assign mat_p_bram_ce0 = grp_mac_Pipeline_VITIS_LOOP_234_1_fu_83_mat_p_bram_ce0;

assign tmp_s_nbwritereq_fu_68_p3 = mac_res_stream_full_n;

endmodule //krnl_bp_mac
