-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_bp_krnl_bp_Pipeline_VITIS_LOOP_642_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    chunk : IN STD_LOGIC_VECTOR (30 downto 0);
    z_old_15_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_15_ce0 : OUT STD_LOGIC;
    z_old_15_we0 : OUT STD_LOGIC;
    z_old_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_14_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_14_ce0 : OUT STD_LOGIC;
    z_old_14_we0 : OUT STD_LOGIC;
    z_old_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_13_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_13_ce0 : OUT STD_LOGIC;
    z_old_13_we0 : OUT STD_LOGIC;
    z_old_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_12_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_12_ce0 : OUT STD_LOGIC;
    z_old_12_we0 : OUT STD_LOGIC;
    z_old_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_11_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_11_ce0 : OUT STD_LOGIC;
    z_old_11_we0 : OUT STD_LOGIC;
    z_old_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_10_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_10_ce0 : OUT STD_LOGIC;
    z_old_10_we0 : OUT STD_LOGIC;
    z_old_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_9_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_9_ce0 : OUT STD_LOGIC;
    z_old_9_we0 : OUT STD_LOGIC;
    z_old_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_8_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_8_ce0 : OUT STD_LOGIC;
    z_old_8_we0 : OUT STD_LOGIC;
    z_old_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_7_ce0 : OUT STD_LOGIC;
    z_old_7_we0 : OUT STD_LOGIC;
    z_old_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_6_ce0 : OUT STD_LOGIC;
    z_old_6_we0 : OUT STD_LOGIC;
    z_old_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_5_ce0 : OUT STD_LOGIC;
    z_old_5_we0 : OUT STD_LOGIC;
    z_old_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_4_ce0 : OUT STD_LOGIC;
    z_old_4_we0 : OUT STD_LOGIC;
    z_old_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_3_ce0 : OUT STD_LOGIC;
    z_old_3_we0 : OUT STD_LOGIC;
    z_old_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_2_ce0 : OUT STD_LOGIC;
    z_old_2_we0 : OUT STD_LOGIC;
    z_old_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_1_ce0 : OUT STD_LOGIC;
    z_old_1_we0 : OUT STD_LOGIC;
    z_old_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_old_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_old_ce0 : OUT STD_LOGIC;
    z_old_we0 : OUT STD_LOGIC;
    z_old_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    z_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_ce0 : OUT STD_LOGIC;
    z_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_1_ce0 : OUT STD_LOGIC;
    z_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_2_ce0 : OUT STD_LOGIC;
    z_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_3_ce0 : OUT STD_LOGIC;
    z_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_4_ce0 : OUT STD_LOGIC;
    z_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_5_ce0 : OUT STD_LOGIC;
    z_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_6_ce0 : OUT STD_LOGIC;
    z_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_7_ce0 : OUT STD_LOGIC;
    z_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_8_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_8_ce0 : OUT STD_LOGIC;
    z_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_9_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_9_ce0 : OUT STD_LOGIC;
    z_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_10_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_10_ce0 : OUT STD_LOGIC;
    z_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_11_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_11_ce0 : OUT STD_LOGIC;
    z_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_12_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_12_ce0 : OUT STD_LOGIC;
    z_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_13_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_13_ce0 : OUT STD_LOGIC;
    z_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_14_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_14_ce0 : OUT STD_LOGIC;
    z_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    z_15_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    z_15_ce0 : OUT STD_LOGIC;
    z_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of krnl_bp_krnl_bp_Pipeline_VITIS_LOOP_642_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln642_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln642_fu_564_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln642_reg_716 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal z_old_addr_reg_801 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_1_addr_reg_806 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_2_addr_reg_811 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_3_addr_reg_816 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_4_addr_reg_821 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_5_addr_reg_826 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_6_addr_reg_831 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_7_addr_reg_836 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_8_addr_reg_841 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_9_addr_reg_846 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_10_addr_reg_851 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_11_addr_reg_856 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_12_addr_reg_861 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_13_addr_reg_866 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_14_addr_reg_871 : STD_LOGIC_VECTOR (2 downto 0);
    signal z_old_15_addr_reg_876 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln642_fu_578_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_134 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln642_fu_558_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_619_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln6_fu_568_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_619_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_5_fu_619_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_619_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component krnl_bp_sparsemux_33_4_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_bp_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_32_1_1_U156 : component krnl_bp_sparsemux_33_4_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 32,
        CASE1 => "0001",
        din1_WIDTH => 32,
        CASE2 => "0010",
        din2_WIDTH => 32,
        CASE3 => "0011",
        din3_WIDTH => 32,
        CASE4 => "0100",
        din4_WIDTH => 32,
        CASE5 => "0101",
        din5_WIDTH => 32,
        CASE6 => "0110",
        din6_WIDTH => 32,
        CASE7 => "0111",
        din7_WIDTH => 32,
        CASE8 => "1000",
        din8_WIDTH => 32,
        CASE9 => "1001",
        din9_WIDTH => 32,
        CASE10 => "1010",
        din10_WIDTH => 32,
        CASE11 => "1011",
        din11_WIDTH => 32,
        CASE12 => "1100",
        din12_WIDTH => 32,
        CASE13 => "1101",
        din13_WIDTH => 32,
        CASE14 => "1110",
        din14_WIDTH => 32,
        CASE15 => "1111",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => z_q0,
        din1 => z_1_q0,
        din2 => z_2_q0,
        din3 => z_3_q0,
        din4 => z_4_q0,
        din5 => z_5_q0,
        din6 => z_6_q0,
        din7 => z_7_q0,
        din8 => z_8_q0,
        din9 => z_9_q0,
        din10 => z_10_q0,
        din11 => z_11_q0,
        din12 => z_12_q0,
        din13 => z_13_q0,
        din14 => z_14_q0,
        din15 => z_15_q0,
        def => tmp_5_fu_619_p33,
        sel => trunc_ln642_reg_716,
        dout => tmp_5_fu_619_p35);

    flow_control_loop_pipe_sequential_init_U : component krnl_bp_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln642_fu_552_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_134 <= add_ln642_fu_558_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_134 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln642_reg_716 <= trunc_ln642_fu_564_p1;
                z_old_10_addr_reg_851 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_11_addr_reg_856 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_12_addr_reg_861 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_13_addr_reg_866 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_14_addr_reg_871 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_15_addr_reg_876 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_1_addr_reg_806 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_2_addr_reg_811 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_3_addr_reg_816 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_4_addr_reg_821 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_5_addr_reg_826 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_6_addr_reg_831 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_7_addr_reg_836 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_8_addr_reg_841 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_9_addr_reg_846 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
                z_old_addr_reg_801 <= zext_ln642_fu_578_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln642_fu_558_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln642_fu_552_p2)
    begin
        if (((icmp_ln642_fu_552_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_134, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_134;
        end if; 
    end process;

    icmp_ln642_fu_552_p2 <= "1" when (ap_sig_allocacmp_i_5 = chunk) else "0";
    lshr_ln6_fu_568_p4 <= ap_sig_allocacmp_i_5(6 downto 4);
    tmp_5_fu_619_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln642_fu_564_p1 <= ap_sig_allocacmp_i_5(4 - 1 downto 0);
    z_10_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_10_ce0 <= ap_const_logic_1;
        else 
            z_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_11_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_11_ce0 <= ap_const_logic_1;
        else 
            z_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_12_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_12_ce0 <= ap_const_logic_1;
        else 
            z_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_13_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_13_ce0 <= ap_const_logic_1;
        else 
            z_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_14_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_14_ce0 <= ap_const_logic_1;
        else 
            z_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_15_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_15_ce0 <= ap_const_logic_1;
        else 
            z_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_1_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_1_ce0 <= ap_const_logic_1;
        else 
            z_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_2_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_2_ce0 <= ap_const_logic_1;
        else 
            z_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_3_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_3_ce0 <= ap_const_logic_1;
        else 
            z_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_4_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_4_ce0 <= ap_const_logic_1;
        else 
            z_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_5_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_5_ce0 <= ap_const_logic_1;
        else 
            z_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_6_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_6_ce0 <= ap_const_logic_1;
        else 
            z_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_7_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_7_ce0 <= ap_const_logic_1;
        else 
            z_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_8_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_8_ce0 <= ap_const_logic_1;
        else 
            z_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_9_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_9_ce0 <= ap_const_logic_1;
        else 
            z_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_address0 <= zext_ln642_fu_578_p1(3 - 1 downto 0);

    z_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_ce0 <= ap_const_logic_1;
        else 
            z_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_10_address0 <= z_old_10_addr_reg_851;

    z_old_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_10_ce0 <= ap_const_logic_1;
        else 
            z_old_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_10_d0 <= tmp_5_fu_619_p35;

    z_old_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_10_we0 <= ap_const_logic_1;
        else 
            z_old_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_11_address0 <= z_old_11_addr_reg_856;

    z_old_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_11_ce0 <= ap_const_logic_1;
        else 
            z_old_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_11_d0 <= tmp_5_fu_619_p35;

    z_old_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_11_we0 <= ap_const_logic_1;
        else 
            z_old_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_12_address0 <= z_old_12_addr_reg_861;

    z_old_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_12_ce0 <= ap_const_logic_1;
        else 
            z_old_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_12_d0 <= tmp_5_fu_619_p35;

    z_old_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_12_we0 <= ap_const_logic_1;
        else 
            z_old_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_13_address0 <= z_old_13_addr_reg_866;

    z_old_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_13_ce0 <= ap_const_logic_1;
        else 
            z_old_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_13_d0 <= tmp_5_fu_619_p35;

    z_old_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_13_we0 <= ap_const_logic_1;
        else 
            z_old_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_14_address0 <= z_old_14_addr_reg_871;

    z_old_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_14_ce0 <= ap_const_logic_1;
        else 
            z_old_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_14_d0 <= tmp_5_fu_619_p35;

    z_old_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_14_we0 <= ap_const_logic_1;
        else 
            z_old_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_15_address0 <= z_old_15_addr_reg_876;

    z_old_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_15_ce0 <= ap_const_logic_1;
        else 
            z_old_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_15_d0 <= tmp_5_fu_619_p35;

    z_old_15_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_15_we0 <= ap_const_logic_1;
        else 
            z_old_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_1_address0 <= z_old_1_addr_reg_806;

    z_old_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_1_ce0 <= ap_const_logic_1;
        else 
            z_old_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_1_d0 <= tmp_5_fu_619_p35;

    z_old_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_1_we0 <= ap_const_logic_1;
        else 
            z_old_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_2_address0 <= z_old_2_addr_reg_811;

    z_old_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_2_ce0 <= ap_const_logic_1;
        else 
            z_old_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_2_d0 <= tmp_5_fu_619_p35;

    z_old_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_2_we0 <= ap_const_logic_1;
        else 
            z_old_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_3_address0 <= z_old_3_addr_reg_816;

    z_old_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_3_ce0 <= ap_const_logic_1;
        else 
            z_old_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_3_d0 <= tmp_5_fu_619_p35;

    z_old_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_3_we0 <= ap_const_logic_1;
        else 
            z_old_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_4_address0 <= z_old_4_addr_reg_821;

    z_old_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_4_ce0 <= ap_const_logic_1;
        else 
            z_old_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_4_d0 <= tmp_5_fu_619_p35;

    z_old_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_4_we0 <= ap_const_logic_1;
        else 
            z_old_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_5_address0 <= z_old_5_addr_reg_826;

    z_old_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_5_ce0 <= ap_const_logic_1;
        else 
            z_old_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_5_d0 <= tmp_5_fu_619_p35;

    z_old_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_5_we0 <= ap_const_logic_1;
        else 
            z_old_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_6_address0 <= z_old_6_addr_reg_831;

    z_old_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_6_ce0 <= ap_const_logic_1;
        else 
            z_old_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_6_d0 <= tmp_5_fu_619_p35;

    z_old_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_6_we0 <= ap_const_logic_1;
        else 
            z_old_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_7_address0 <= z_old_7_addr_reg_836;

    z_old_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_7_ce0 <= ap_const_logic_1;
        else 
            z_old_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_7_d0 <= tmp_5_fu_619_p35;

    z_old_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_7_we0 <= ap_const_logic_1;
        else 
            z_old_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_8_address0 <= z_old_8_addr_reg_841;

    z_old_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_8_ce0 <= ap_const_logic_1;
        else 
            z_old_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_8_d0 <= tmp_5_fu_619_p35;

    z_old_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_8_we0 <= ap_const_logic_1;
        else 
            z_old_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_9_address0 <= z_old_9_addr_reg_846;

    z_old_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_9_ce0 <= ap_const_logic_1;
        else 
            z_old_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_9_d0 <= tmp_5_fu_619_p35;

    z_old_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_9_we0 <= ap_const_logic_1;
        else 
            z_old_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_address0 <= z_old_addr_reg_801;

    z_old_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_ce0 <= ap_const_logic_1;
        else 
            z_old_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    z_old_d0 <= tmp_5_fu_619_p35;

    z_old_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln642_reg_716, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln642_reg_716 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            z_old_we0 <= ap_const_logic_1;
        else 
            z_old_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln642_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln6_fu_568_p4),64));
end behav;
